version: '3'
services:
  mellivora:
    image: mellivora
    ports:
      - 4040:80
      - 4042:443
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MELLIVORA_CONFIG_DB_ENGINE: mysql
      MELLIVORA_CONFIG_DB_HOST: db
      MELLIVORA_CONFIG_DB_PORT: 3306
      MELLIVORA_CONFIG_DB_NAME: PCTF21
      MELLIVORA_CONFIG_DB_USER: PCTF21_root
      MELLIVORA_CONFIG_DB_PASSWORD: FWEBFREWI232nbkjfvger2r2bjed
    volumes:
      - .:/var/www/mellivora
      - composerdependencies:/var/www/mellivora/include/thirdparty/composer
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: PCTF21
      MYSQL_USER: PCTF21_root
      MYSQL_PASSWORD: FWEBFREWI232nbkjfvger2r2bjed
      MYSQL_ROOT_PASSWORD: JNGVEB2341R45jsbfgvb21fne
    volumes:
      - dbdata:/var/lib/mysql
      - ./install/sql:/docker-entrypoint-initdb.d
  adminer:
      image: adminer
      restart: always
      ports:
        - 18080:8080
volumes:
  composerdependencies:
  dbdata: